import { StyleSheet, Platform, Dimensions } from "react-native";

const { width } = Dimensions.get("window");

export const styles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: "#0b0f19",
    paddingTop: Platform.OS === "android" ? 30 : 0,
  },
  loadingContainer: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
  },
  loadingText: {
    color: "#94a3b8",
    fontSize: 14,
    marginTop: 10,
  },
  header: {
    height: 60,
    borderBottomWidth: 1,
    borderBottomColor: "#1e293b",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 16,
  },
  headerTitleContainer: {
    flexDirection: "row",
    alignItems: "center",
    flex: 1,
  },
  headerEmoji: {
    fontSize: 20,
    marginRight: 6,
  },
  headerText: {
    color: "#fff",
    fontSize: 18,
    fontWeight: "900",
    letterSpacing: -0.5,
  },
  badge: {
    backgroundColor: "rgba(251, 191, 36, 0.1)",
    borderWidth: 1,
    borderColor: "rgba(251, 191, 36, 0.2)",
    paddingHorizontal: 8,
    paddingVertical: 2,
    borderRadius: 999,
    marginLeft: 8,
  },
  badgeText: {
    color: "#fbbf24",
    fontSize: 9,
    fontWeight: "bold",
  },
  refreshButton: {
    padding: 8,
  },
  refreshButtonText: {
    color: "#10b981",
    fontSize: 20,
    fontWeight: "bold",
  },
  tabContainer: {
    flexDirection: "row",
    paddingHorizontal: 16,
    paddingVertical: 8,
    borderBottomWidth: 1,
    borderBottomColor: "#1e293b",
  },
  tabButton: {
    flex: 1,
    alignItems: "center",
    paddingVertical: 8,
    borderBottomWidth: 2,
    borderBottomColor: "transparent",
  },
  tabButtonActive: {
    borderBottomColor: "#10b981",
  },
  tabButtonText: {
    color: "#94a3b8",
    fontSize: 9,
    fontWeight: "750",
  },
  tabButtonTextActive: {
    color: "#10b981",
  },
  contentContainer: {
    flex: 1,
    padding: 16,
  },
  countdownCard: {
    backgroundColor: "#131b2e",
    borderWidth: 1,
    borderColor: "#1e293b",
    borderRadius: 16,
    padding: 16,
    marginBottom: 20,
  },
  concludedCard: {
    backgroundColor: "#131b2e",
    borderWidth: 1,
    borderColor: "#f59e0b",
    borderRadius: 16,
    padding: 20,
    marginBottom: 20,
    alignItems: "center",
    justifyContent: "center",
  },
  concludedTitle: {
    color: "#94a3b8",
    fontSize: 10,
    fontWeight: "bold",
    letterSpacing: 1,
    marginBottom: 12,
  },
  winnerBadge: {
    backgroundColor: "rgba(245, 158, 11, 0.1)",
    borderWidth: 1,
    borderColor: "rgba(245, 158, 11, 0.3)",
    paddingVertical: 8,
    paddingHorizontal: 20,
    borderRadius: 12,
  },
  winnerBadgeText: {
    color: "#fbbf24",
    fontWeight: "900",
    fontSize: 13,
    letterSpacing: 1.5,
  },
  countdownTitle: {
    color: "#fbbf24",
    fontSize: 10,
    fontWeight: "bold",
    letterSpacing: 1,
    marginBottom: 12,
  },
  countdownRow: {
    flexDirection: "row",
    justifyContent: "space-between",
  },
  countdownCol: {
    alignItems: "center",
    flex: 1,
  },
  countdownVal: {
    color: "#fff",
    fontSize: 28,
    fontWeight: "900",
  },
  countdownLbl: {
    color: "#94a3b8",
    fontSize: 9,
    fontWeight: "bold",
    marginTop: 2,
  },
  section: {
    marginBottom: 30,
  },
  sectionBlock: {
    marginBottom: 20,
  },
  sectionHeaderRow: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 12,
  },
  liveIndicatorDot: {
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: "#ef4444",
    marginRight: 6,
  },
  sectionTitleLive: {
    color: "#ef4444",
    fontSize: 12,
    fontWeight: "bold",
    letterSpacing: 0.5,
  },
  sectionTitleFav: {
    color: "#fbbf24",
    fontSize: 12,
    fontWeight: "bold",
    letterSpacing: 0.5,
    marginBottom: 12,
  },
  sectionTitle: {
    color: "#10b981",
    fontSize: 12,
    fontWeight: "bold",
    letterSpacing: 0.5,
    marginBottom: 12,
  },
  liveScroll: {
    flexDirection: "row",
  },
  liveCard: {
    backgroundColor: "#131b2e",
    borderWidth: 1,
    borderColor: "rgba(16, 185, 129, 0.2)",
    borderRadius: 16,
    padding: 16,
    marginRight: 12,
    width: width * 0.75,
  },
  liveCardHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginBottom: 10,
  },
  liveCardGroup: {
    color: "#94a3b8",
    fontSize: 10,
    fontWeight: "bold",
  },
  liveCardTime: {
    color: "#ef4444",
    fontSize: 10,
    fontWeight: "bold",
  },
  liveCardTeamsRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  liveCardTeam: {
    alignItems: "center",
    width: "35%",
  },
  flag: {
    fontSize: 32,
    marginBottom: 4,
  },
  teamName: {
    color: "#fff",
    fontSize: 12,
    fontWeight: "750",
  },
  liveCardScoreContainer: {
    backgroundColor: "#0b0f19",
    borderWidth: 1,
    borderColor: "#1e293b",
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 8,
  },
  liveCardScore: {
    color: "#fff",
    fontSize: 18,
    fontWeight: "900",
    letterSpacing: 1,
  },
  fixtureCard: {
    backgroundColor: "#131b2e",
    borderWidth: 1,
    borderColor: "#1e293b",
    borderRadius: 12,
    padding: 12,
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 8,
  },
  fixtureTeams: {
    flex: 1,
  },
  fixtureTeamRow: {
    flexDirection: "row",
    alignItems: "center",
    marginVertical: 2,
  },
  fixtureFlag: {
    fontSize: 18,
    marginRight: 8,
  },
  fixtureTeamText: {
    color: "#e2e8f0",
    fontSize: 13,
    fontWeight: "600",
  },
  fixtureTimeBlock: {
    alignItems: "center",
    paddingLeft: 12,
    borderLeftWidth: 1,
    borderLeftColor: "#1e293b",
    width: 70,
  },
  fixtureTime: {
    color: "#10b981",
    fontSize: 13,
    fontWeight: "800",
  },
  fixtureDate: {
    color: "#94a3b8",
    fontSize: 9,
    fontWeight: "600",
    marginTop: 2,
  },
  matchScoreText: {
    color: "#fff",
    fontSize: 14,
    fontWeight: "800",
  },
  groupBlock: {
    backgroundColor: "#131b2e",
    borderWidth: 1,
    borderColor: "#1e293b",
    borderRadius: 16,
    padding: 16,
    marginBottom: 16,
  },
  groupTitle: {
    color: "#10b981",
    fontSize: 13,
    fontWeight: "bold",
    marginBottom: 12,
  },
  tableHeader: {
    flexDirection: "row",
    borderBottomWidth: 1,
    borderBottomColor: "#1e293b",
    paddingBottom: 6,
    marginBottom: 6,
  },
  th: {
    color: "#94a3b8",
    fontSize: 9,
    fontWeight: "bold",
  },
  thCenter: {
    textAlign: "center",
    width: 32,
  },
  tableRow: {
    flexDirection: "row",
    alignItems: "center",
    paddingVertical: 6,
    borderBottomWidth: 1,
    borderBottomColor: "rgba(30, 41, 59, 0.3)",
  },
  tableTeamCell: {
    flexDirection: "row",
    alignItems: "center",
    flex: 1,
  },
  tableRank: {
    color: "#94a3b8",
    fontSize: 11,
    fontWeight: "bold",
    marginRight: 6,
    width: 14,
  },
  tableFlag: {
    fontSize: 16,
    marginRight: 6,
  },
  tableTeamText: {
    color: "#fff",
    fontSize: 12,
    fontWeight: "750",
  },
  td: {
    color: "#e2e8f0",
    fontSize: 11,
  },
  tdCenter: {
    textAlign: "center",
    width: 32,
  },
  tdPoints: {
    color: "#10b981",
    fontWeight: "900",
  },
  predHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 16,
  },
  pointsBadge: {
    backgroundColor: "rgba(16, 185, 129, 0.1)",
    borderWidth: 1,
    borderColor: "rgba(16, 185, 129, 0.2)",
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 8,
    flexDirection: "row",
    alignItems: "center",
  },
  pointsLabel: {
    color: "#94a3b8",
    fontSize: 10,
    fontWeight: "bold",
  },
  pointsText: {
    color: "#10b981",
    fontSize: 12,
    fontWeight: "950",
  },
  predCard: {
    backgroundColor: "#131b2e",
    borderWidth: 1,
    borderColor: "#1e293b",
    borderRadius: 16,
    padding: 16,
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 12,
  },
  predTeamsColumn: {
    flex: 1,
  },
  predTeamRow: {
    flexDirection: "row",
    alignItems: "center",
  },
  predInputsRow: {
    flexDirection: "row",
    alignItems: "center",
  },
  predInput: {
    backgroundColor: "#0b0f19",
    borderWidth: 1,
    borderColor: "#1e293b",
    width: 45,
    height: 40,
    borderRadius: 8,
    color: "#fff",
    textAlign: "center",
    fontSize: 16,
    fontWeight: "bold",
  },
  predColon: {
    color: "#64748b",
    marginHorizontal: 6,
    fontSize: 16,
    fontWeight: "bold",
  },
  footer: {
    marginTop: 20,
    marginBottom: 40,
    paddingTop: 16,
    borderTopWidth: 1,
    borderTopColor: "rgba(30, 41, 59, 0.3)",
    alignItems: "center",
  },
  footerText: {
    color: "#475569",
    fontSize: 11,
    fontWeight: "500",
  },
});
